# Add your own tasks in files placed in lib/tasks ending in .rake,
$: << File.expand_path('../lib',__FILE__)
require 'duper_clock'
require 'rake'
require 'rake/testtask'

desc 'Default: Run unit tests.'
task :default => :test

desc 'Run unit tests.'
Rake::TestTask.new(:test) do |t|
  t.libs << 'lib'
  t.libs << 'test'
  t.pattern = 'test/**/*_test.rb'
  t.verbose = true
end

desc 'Ejecutar ventana'
task :ventana do 
	DuperClock::Window.new.main_loop
end