# Add your own tasks in files placed in lib/tasks ending in .rake,
require 'rake'
require 'rake/testtask'

desc 'Default: Run unit tests.'
task :default => :test

desc 'Run unit tests.'
Rake::TestTask.new(:test) do |t|
  t.libs << 'lib'
  t.libs << 'test'
  t.pattern = 'test/**/*_test.rb'
  t.verbose = true
end
